[system]
python_interpreter = "python3"

[database]
# Define your connection parameters
server = "192.168.2.50:1433\\wiffzack"
database = "wiffzack"
username = "wiffzack"
password = "wiffzack"

[server]
host = "localhost"
port = 5000
debug = false
init_stock_directory = "assets/init/"

[alarm]
url = "http://192.168.202.1/alarm_trigger.php?location={location}"


[checklist]
# a new checklist expires after that amount of minutes
expiry_mins = 30


[terminal_config]

[terminal_config.lager]
name = "lager"
storage_id = 0

[terminal_config.bar1]
name = "bar1"
request_storage_id = 1
transfer_storage_id = 2
storage_id = 3
